version: "3"
services:
    game-server:
        image: coderone.azurecr.io/game-server:1663
        volumes:
            - ./logs:/app/logs

    go-agent:
        build:
            context: go
            dockerfile: Dockerfile

    agent:
        build:
            context: python3
            dockerfile: Dockerfile

    agent-dev:
        build:
            context: python3
            dockerfile: Dockerfile.dev
        volumes:
            - ./python3:/app

    random-agent:
        build:
            context: python3
            dockerfile: Dockerfile.random

    rule-agent:
        build:
            context: python3
            dockerfile: Dockerfile.rule

    nn-agent:
        build:
            context: python3
            dockerfile: Dockerfile.nn

    rule-agent-dev:
        build:
            context: python3
            dockerfile: Dockerfile.rule.dev
        volumes:
            - ./python3:/app

    python3-fwd:
        build:
            context: python3
            dockerfile: Dockerfile.fwd

    python3-fwd-dev:
        build:
            context: python3
            dockerfile: Dockerfile.fwd.dev
        volumes:
            - ./python3:/app
    python3-gym-dev:
        build:
            context: python3
            dockerfile: Dockerfile.gym.dev
        volumes:
            - ./python3:/app

    typescript-agent:
        build:
            context: typescript
            dockerfile: Dockerfile

    typescript-agent-dev:
        build:
            context: typescript
            dockerfile: Dockerfile.dev
        volumes:
            - ./typescript:/app

    cpp-agent:
        build:
            context: cpp
            dockerfile: Dockerfile

    rust-agent:
        build:
            context: rust
            dockerfile: Dockerfile

    published-agent:
        image: docker.io/opryzhek/bombermann:good-search-2

    il-agent:
        image: docker.io/opryzhek/bombermann:il-1

    enemy-agent:
        image: public.docker.cloudgamepad.com/gocoder/f439u384k4554etg-baseline
